### ISSUE TITLE
Segmentation fault on non-existent image node

### ISSUE THREAD

**Issue by bluebrown** [bluebrown/kobold#7]
When a repostiry contains a yaml file that looks like a valid resource but is missing the actual image node, the below panic is thorwn

For example, having a yaml file with the following content:

```yaml
spec:
  volumes:
  - name: emqx-mtls-secret
    secret:
      secretName: emqx-mtls-secret
  containers:
  - name: emqx-container
    volumeMounts:
    - name: emqx-mtls-secret
      mountPath: /tmp/ssl/tls.crt
    - name: emqx-mtls-secret
      mountPath: /tmp/ssl/tls.key
```

```c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb89773]

goroutine 68 [running]:
github.com/bluebrown/kobold/internal/krm.(*ImageNodeHandler).HandleImageNode(0xc00141a8e0?, 0x0?, {0xc0008b8000?, 0xc000681768?, 0x0?})
        github.com/bluebrown/kobold/internal/krm/krm.go:132 +0x53
github.com/bluebrown/kobold/internal/krm.(*filter).imageNodeHandler(0xc000e19a90, {0xc00127bcd0, 0x2c}, {0xc001316b00, 0xe}, 0x0?)
        github.com/bluebrown/kobold/internal/krm/renderer.go:192 +0x94
github.com/bluebrown/kobold/internal/krm.resolveKube.func1(0xc002687a40?)
        github.com/bluebrown/kobold/internal/krm/renderer.go:234 +0x9f
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).VisitElements(0xc000e8d3c0?, 0xc0006818d8)
        sigs.k8s.io/kustomize/kyaml@v0.13.10/yaml/rnode.go:843 +0x9d
github.com/bluebrown/kobold/internal/krm.resolveKube(0x204ec38?, {0xc00127bcd0, 0x2c}, 0xc00044ea10)
        github.com/bluebrown/kobold/internal/krm/renderer.go:228 +0xc8
github.com/bluebrown/kobold/internal/krm.(*filter).Filter(0xc000e19a90, {0xc00157c000?, 0x82, 0x90})
        github.com/bluebrown/kobold/internal/krm/renderer.go:182 +0x1b2
sigs.k8s.io/kustomize/kyaml/kio.Pipeline.ExecuteWithCallback({{0xc000681ab8, 0x1, 0x1}, {0xc000681aa8, 0x1, 0x1}, {0xc000681a98, 0x1, 0x1}, 0x0}, ...)
        sigs.k8s.io/kustomize/kyaml@v0.13.10/kio/kio.go:137 +0x13f
sigs.k8s.io/kustomize/kyaml/kio.Pipeline.Execute(...)
        sigs.k8s.io/kustomize/kyaml@v0.13.10/kio/kio.go:104
github.com/bluebrown/kobold/internal/krm.renderer.Render({0xc0018ad6b0, 0xc000ee2ca0, {0x1d96346, 0xf}, 0xc000ee2c80, {0x2036820, 0xc0001319e0}}, {0x204ec38, 0xc001580f30}, {0xc00016beb0, ...}, ...)
        github.com/bluebrown/kobold/internal/krm/renderer.go:148 +0x3da
github.com/bluebrown/kobold/internal/server.NewSubscriber.func1.1({0x204ec38?, 0xc001580f30?}, {0xc00016beb0?, 0xc00016af80?})
        github.com/bluebrown/kobold/internal/server/webhooks.go:110 +0x6a
github.com/bluebrown/kobold/internal/gitbot.(*GitBot).Do.func1({0xc00016beb0, 0xf}, {0x2051630, 0xc0004233c0})
        github.com/bluebrown/kobold/internal/gitbot/bot.go:90 +0xc2
github.com/bluebrown/kobold/internal/gitbot.(*repo).Transactions(0xc00153be00, 0xc000073630)
        github.com/bluebrown/kobold/internal/gitbot/bot.go:50 +0xba
github.com/bluebrown/kobold/internal/gitbot.(*GitBot).Do(0x2041710?, {0x204ec38?, 0xc001580f30?}, 0x0?)
        github.com/bluebrown/kobold/internal/gitbot/bot.go:83 +0x5d
github.com/bluebrown/kobold/internal/server.NewSubscriber.func1()
        github.com/bluebrown/kobold/internal/server/webhooks.go:109 +0x490
created by github.com/bluebrown/kobold/internal/server.NewSubscriber
        github.com/bluebrown/kobold/internal/server/webhooks.go:87 +0x432
```

**Comment by bluebrown** [comment]
resolved by #37
